{{- if and .Values.kedaAutoScaling.enabled (eq .Values.queueAdapter "good_job") .Values.kedaAutoScaling.postgres.autoCreateRole }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "match.kedaPostgresRoleSecretName" . }}
  labels:
    {{- include "match.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "match.kedaPostgresRolePassword" . | b64enc }}
{{- end }}
