apiVersion: batch/v1
kind: Job
metadata:
  name: rails-prepare-job-{{ .Release.Revision }}
  namespace: match
  annotations:
    {{- with .Values.dbPrepareJob.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.useArgoSyncWaveAnnotations }}
    {{- toYaml .Values.dbPrepareJob.argoSyncWaveAnnotations | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.dbPrepareJob.helmHookAnnotations | nindent 4 }}
    {{- end }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "match.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: rails-db-prepare
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/bash", "-c", "bin/rails db:prepare"]
          env:
           {{- include "match.envVars" . | nindent 12 }}
           {{- include "match.owningUserEnvVars" . | nindent 12 }}
          volumeMounts:
           {{- toYaml .Values.volumeMounts | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}