{{- if eq .Values.metrics.enabled true }}
{{- range $name, $worker := .Values.workers }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $name }}-worker-{{ include "match.fullname" $ }}
  labels:
    {{- include "match.labels" $ | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "match.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}-worker
  podMetricsEndpoints:
    - port: "metrics"
{{- end }}
{{- end }}